markdown:           kramdown
highlighter:        rouge
plugins:
    - jekyll-sitemap

# we generate those files ourselves
exclude:
    - "*.css"
    - "*.js"

# permalinks
permalink:          date

# server
source:             source
destination:        dist
port:               8000
url:                https://tortoisesvn.net
encoding:           UTF-8

# custom variables
version:
  short:            1.9.7
  long:             1.9.7.27907
  svn:              1.9.7

description:        The coolest interface to (Sub)version control
