markdown:           kramdown
highlighter:        rouge
gems:
  - jekyll-sitemap

# we generate those files ourselves
exclude:
  - "*.css"
  - "*.js"
  - "_old-flags"

# permalinks
permalink:          date

# server
source:             source
destination:        dist
port:               8000
url:                https://tortoisesvn.net
encoding:           UTF-8

# custom variables
version:
  short:            1.9.5
  long:             1.9.5.27581
  svn:              1.9.5

description:        The coolest interface to (Sub)version control
