markdown:           kramdown
highlighter:        rouge
plugins:
    - jekyll-sitemap

# we generate those files ourselves
exclude:
    - "*.css"
    - "*.js"

# permalinks
permalink:          date

# server
source:             source
destination:        dist
port:               8000
url:                https://tortoisesvn.net
encoding:           UTF-8

# custom variables
version:
  short:            1.12.1
  long:             1.12.1.28628
  svn:              1.12.2

version-pre:
  short:            1.10.4
  long:             1.10.4.28626
  svn:              1.10.6

description:        The coolest interface to (Sub)version control
